
package com.web.utils.suma;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2012-06-28T16:35:20.906+08:00
 * Generated source version: 2.3.7
 * 
 */
public final class LinkWSSoap_LinkWSSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "LinkWS");

    private LinkWSSoap_LinkWSSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LinkWS.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LinkWS ss = new LinkWS(wsdlURL, SERVICE_NAME);
        LinkWSSoap port = ss.getLinkWSSoap();  
        
        {
        System.out.println("Invoking chargeUpMMS...");
        java.lang.String _chargeUpMMS_corpID = "";
        java.lang.String _chargeUpMMS_pwd = "";
        java.lang.String _chargeUpMMS_cardNo = "";
        java.lang.String _chargeUpMMS_cardPwd = "";
        java.lang.String _chargeUpMMS__return = port.chargeUpMMS(_chargeUpMMS_corpID, _chargeUpMMS_pwd, _chargeUpMMS_cardNo, _chargeUpMMS_cardPwd);
        System.out.println("chargeUpMMS.result=" + _chargeUpMMS__return);


        }
        {
        System.out.println("Invoking agentMakeAccount...");
        java.lang.String _agentMakeAccount_loginName = "";
        java.lang.String _agentMakeAccount_loginPwd = "";
        java.lang.String _agentMakeAccount_corpName = "";
        java.lang.String _agentMakeAccount_linkMan = "";
        java.lang.String _agentMakeAccount_tel = "";
        java.lang.String _agentMakeAccount_mobile = "";
        java.lang.String _agentMakeAccount_email = "";
        java.lang.String _agentMakeAccount_memo = "";
        java.lang.String _agentMakeAccount_corpID = "";
        java.lang.String _agentMakeAccount_pass = "";
        java.lang.String _agentMakeAccount__return = port.agentMakeAccount(_agentMakeAccount_loginName, _agentMakeAccount_loginPwd, _agentMakeAccount_corpName, _agentMakeAccount_linkMan, _agentMakeAccount_tel, _agentMakeAccount_mobile, _agentMakeAccount_email, _agentMakeAccount_memo, _agentMakeAccount_corpID, _agentMakeAccount_pass);
        System.out.println("agentMakeAccount.result=" + _agentMakeAccount__return);


        }
        {
        System.out.println("Invoking helloWorld...");
        java.lang.String _helloWorld__return = port.helloWorld();
        System.out.println("helloWorld.result=" + _helloWorld__return);


        }
        {
        System.out.println("Invoking getReportFail...");
        java.lang.String _getReportFail_corpID = "";
        java.lang.String _getReportFail_pwd = "";
        java.lang.String _getReportFail_cell = "";
        java.lang.String _getReportFail__return = port.getReportFail(_getReportFail_corpID, _getReportFail_pwd, _getReportFail_cell);
        System.out.println("getReportFail.result=" + _getReportFail__return);


        }
        {
        System.out.println("Invoking getMMS...");
        java.lang.String _getMMS_corpID = "";
        java.lang.String _getMMS_pwd = "";
        java.lang.String _getMMS__return = port.getMMS(_getMMS_corpID, _getMMS_pwd);
        System.out.println("getMMS.result=" + _getMMS__return);


        }
        {
        System.out.println("Invoking agentChangeAccount...");
        java.lang.String _agentChangeAccount_loginName = "";
        java.lang.String _agentChangeAccount_loginPwd = "";
        java.lang.String _agentChangeAccount_corpID = "";
        int _agentChangeAccount_smsBalance = 0;
        int _agentChangeAccount_mmsBalance = 0;
        java.lang.String _agentChangeAccount__return = port.agentChangeAccount(_agentChangeAccount_loginName, _agentChangeAccount_loginPwd, _agentChangeAccount_corpID, _agentChangeAccount_smsBalance, _agentChangeAccount_mmsBalance);
        System.out.println("agentChangeAccount.result=" + _agentChangeAccount__return);


        }
        {
        System.out.println("Invoking chargeUp...");
        java.lang.String _chargeUp_corpID = "";
        java.lang.String _chargeUp_pwd = "";
        java.lang.String _chargeUp_cardNo = "";
        java.lang.String _chargeUp_cardPwd = "";
        int _chargeUp__return = port.chargeUp(_chargeUp_corpID, _chargeUp_pwd, _chargeUp_cardNo, _chargeUp_cardPwd);
        System.out.println("chargeUp.result=" + _chargeUp__return);


        }
        {
        System.out.println("Invoking reg...");
        java.lang.String _reg_corpID = "";
        java.lang.String _reg_pwd = "";
        java.lang.String _reg_corpName = "";
        java.lang.String _reg_linkMan = "";
        java.lang.String _reg_tel = "";
        java.lang.String _reg_mobile = "";
        java.lang.String _reg_email = "";
        java.lang.String _reg_memo = "";
        int _reg__return = port.reg(_reg_corpID, _reg_pwd, _reg_corpName, _reg_linkMan, _reg_tel, _reg_mobile, _reg_email, _reg_memo);
        System.out.println("reg.result=" + _reg__return);


        }
        {
        System.out.println("Invoking updPwd...");
        java.lang.String _updPwd_corpID = "";
        java.lang.String _updPwd_pwd = "";
        java.lang.String _updPwd_newPwd = "";
        int _updPwd__return = port.updPwd(_updPwd_corpID, _updPwd_pwd, _updPwd_newPwd);
        System.out.println("updPwd.result=" + _updPwd__return);


        }
        {
        System.out.println("Invoking unReg...");
        java.lang.String _unReg_corpID = "";
        java.lang.String _unReg_pwd = "";
        int _unReg__return = port.unReg(_unReg_corpID, _unReg_pwd);
        System.out.println("unReg.result=" + _unReg__return);


        }
        {
        System.out.println("Invoking getReportSMS...");
        java.lang.String _getReportSMS_corpID = "";
        java.lang.String _getReportSMS_pwd = "";
        java.lang.String _getReportSMS__return = port.getReportSMS(_getReportSMS_corpID, _getReportSMS_pwd);
        System.out.println("getReportSMS.result=" + _getReportSMS__return);


        }
        {
        System.out.println("Invoking sendMMS...");
        java.lang.String _sendMMS_corpID = "";
        java.lang.String _sendMMS_pwd = "";
        java.lang.String _sendMMS_mobile = "";
        java.lang.String _sendMMS_base64Content = "";
        java.lang.String _sendMMS_title = "";
        java.lang.String _sendMMS_extCode = "";
        java.lang.String _sendMMS_sendTime = "";
        java.lang.String _sendMMS__return = port.sendMMS(_sendMMS_corpID, _sendMMS_pwd, _sendMMS_mobile, _sendMMS_base64Content, _sendMMS_title, _sendMMS_extCode, _sendMMS_sendTime);
        System.out.println("sendMMS.result=" + _sendMMS__return);


        }
        {
        System.out.println("Invoking send...");
        java.lang.String _send_corpID = "";
        java.lang.String _send_pwd = "";
        java.lang.String _send_mobile = "";
        java.lang.String _send_content = "";
        java.lang.String _send_cell = "";
        java.lang.String _send_sendTime = "";
        int _send__return = port.send(_send_corpID, _send_pwd, _send_mobile, _send_content, _send_cell, _send_sendTime);
        System.out.println("send.result=" + _send__return);


        }
        {
        System.out.println("Invoking send2...");
        java.lang.String _send2_corpID = "";
        java.lang.String _send2_pwd = "";
        java.lang.String _send2_mobile = "";
        java.lang.String _send2_content = "";
        java.lang.String _send2_cell = "";
        java.lang.String _send2_sendTime = "";
        java.lang.String _send2__return = port.send2(_send2_corpID, _send2_pwd, _send2_mobile, _send2_content, _send2_cell, _send2_sendTime);
        System.out.println("send2.result=" + _send2__return);


        }
        {
        System.out.println("Invoking batchSendMMS...");
        java.lang.String _batchSendMMS_corpID = "";
        java.lang.String _batchSendMMS_pwd = "";
        java.lang.String _batchSendMMS_mobiles = "";
        java.lang.String _batchSendMMS_base64Content = "";
        java.lang.String _batchSendMMS_title = "";
        java.lang.String _batchSendMMS_extCode = "";
        java.lang.String _batchSendMMS_sendTime = "";
        java.lang.String _batchSendMMS__return = port.batchSendMMS(_batchSendMMS_corpID, _batchSendMMS_pwd, _batchSendMMS_mobiles, _batchSendMMS_base64Content, _batchSendMMS_title, _batchSendMMS_extCode, _batchSendMMS_sendTime);
        System.out.println("batchSendMMS.result=" + _batchSendMMS__return);


        }
        {
        System.out.println("Invoking sendMMS2...");
        java.lang.String _sendMMS2_corpID = "";
        java.lang.String _sendMMS2_pwd = "";
        java.lang.String _sendMMS2_mobile = "";
        java.lang.String _sendMMS2_base64Content = "";
        java.lang.String _sendMMS2_title = "";
        java.lang.String _sendMMS2_extCode = "";
        java.lang.String _sendMMS2_sendTime = "";
        java.lang.String _sendMMS2__return = port.sendMMS2(_sendMMS2_corpID, _sendMMS2_pwd, _sendMMS2_mobile, _sendMMS2_base64Content, _sendMMS2_title, _sendMMS2_extCode, _sendMMS2_sendTime);
        System.out.println("sendMMS2.result=" + _sendMMS2__return);


        }
        {
        System.out.println("Invoking balanceMMS...");
        java.lang.String _balanceMMS_corpID = "";
        java.lang.String _balanceMMS_pwd = "";
        java.lang.String _balanceMMS__return = port.balanceMMS(_balanceMMS_corpID, _balanceMMS_pwd);
        System.out.println("balanceMMS.result=" + _balanceMMS__return);


        }
        {
        System.out.println("Invoking batchSend...");
        java.lang.String _batchSend_corpID = "";
        java.lang.String _batchSend_pwd = "";
        java.lang.String _batchSend_mobile = "";
        java.lang.String _batchSend_content = "";
        java.lang.String _batchSend_cell = "";
        java.lang.String _batchSend_sendTime = "";
        int _batchSend__return = port.batchSend(_batchSend_corpID, _batchSend_pwd, _batchSend_mobile, _batchSend_content, _batchSend_cell, _batchSend_sendTime);
        System.out.println("batchSend.result=" + _batchSend__return);


        }
        {
        System.out.println("Invoking batchSendMMS2...");
        java.lang.String _batchSendMMS2_corpID = "";
        java.lang.String _batchSendMMS2_pwd = "";
        java.lang.String _batchSendMMS2_mobiles = "";
        java.lang.String _batchSendMMS2_base64Content = "";
        java.lang.String _batchSendMMS2_title = "";
        java.lang.String _batchSendMMS2_extCode = "";
        java.lang.String _batchSendMMS2_sendTime = "";
        java.lang.String _batchSendMMS2__return = port.batchSendMMS2(_batchSendMMS2_corpID, _batchSendMMS2_pwd, _batchSendMMS2_mobiles, _batchSendMMS2_base64Content, _batchSendMMS2_title, _batchSendMMS2_extCode, _batchSendMMS2_sendTime);
        System.out.println("batchSendMMS2.result=" + _batchSendMMS2__return);


        }
        {
        System.out.println("Invoking selSum...");
        java.lang.String _selSum_corpID = "";
        java.lang.String _selSum_pwd = "";
        int _selSum__return = port.selSum(_selSum_corpID, _selSum_pwd);
        System.out.println("selSum.result=" + _selSum__return);


        }
        {
        System.out.println("Invoking getReportMMS...");
        java.lang.String _getReportMMS_corpID = "";
        java.lang.String _getReportMMS_pwd = "";
        java.lang.String _getReportMMS__return = port.getReportMMS(_getReportMMS_corpID, _getReportMMS_pwd);
        System.out.println("getReportMMS.result=" + _getReportMMS__return);


        }
        {
        System.out.println("Invoking updReg...");
        java.lang.String _updReg_corpID = "";
        java.lang.String _updReg_pwd = "";
        java.lang.String _updReg_corpName = "";
        java.lang.String _updReg_linkMan = "";
        java.lang.String _updReg_tel = "";
        java.lang.String _updReg_mobile = "";
        java.lang.String _updReg_email = "";
        java.lang.String _updReg_memo = "";
        int _updReg__return = port.updReg(_updReg_corpID, _updReg_pwd, _updReg_corpName, _updReg_linkMan, _updReg_tel, _updReg_mobile, _updReg_email, _updReg_memo);
        System.out.println("updReg.result=" + _updReg__return);


        }
        {
        System.out.println("Invoking getReportFailMMS...");
        java.lang.String _getReportFailMMS_corpID = "";
        java.lang.String _getReportFailMMS_pwd = "";
        java.lang.String _getReportFailMMS_cell = "";
        java.lang.String _getReportFailMMS__return = port.getReportFailMMS(_getReportFailMMS_corpID, _getReportFailMMS_pwd, _getReportFailMMS_cell);
        System.out.println("getReportFailMMS.result=" + _getReportFailMMS__return);


        }
        {
        System.out.println("Invoking batchSend2...");
        java.lang.String _batchSend2_corpID = "";
        java.lang.String _batchSend2_pwd = "";
        java.lang.String _batchSend2_mobile = "";
        java.lang.String _batchSend2_content = "";
        java.lang.String _batchSend2_cell = "";
        java.lang.String _batchSend2_sendTime = "";
        java.lang.String _batchSend2__return = port.batchSend2(_batchSend2_corpID, _batchSend2_pwd, _batchSend2_mobile, _batchSend2_content, _batchSend2_cell, _batchSend2_sendTime);
        System.out.println("batchSend2.result=" + _batchSend2__return);


        }
        {
        System.out.println("Invoking get...");
        java.lang.String _get_corpID = "";
        java.lang.String _get_pwd = "";
        java.lang.String _get__return = port.get(_get_corpID, _get_pwd);
        System.out.println("get.result=" + _get__return);


        }

        System.exit(0);
    }

}
