package com.web.utils.suma;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2012-06-28T16:35:21.046+08:00
 * Generated source version: 2.3.7
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "LinkWSHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LinkWSHttpGet {

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "ChargeUpMMS")
    public java.lang.String chargeUpMMS(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "CardNo", name = "CardNo", targetNamespace = "")
        java.lang.String cardNo,
        @WebParam(partName = "CardPwd", name = "CardPwd", targetNamespace = "")
        java.lang.String cardPwd
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "AgentMakeAccount")
    public java.lang.String agentMakeAccount(
        @WebParam(partName = "LoginName", name = "LoginName", targetNamespace = "")
        java.lang.String loginName,
        @WebParam(partName = "LoginPwd", name = "LoginPwd", targetNamespace = "")
        java.lang.String loginPwd,
        @WebParam(partName = "CorpName", name = "CorpName", targetNamespace = "")
        java.lang.String corpName,
        @WebParam(partName = "LinkMan", name = "LinkMan", targetNamespace = "")
        java.lang.String linkMan,
        @WebParam(partName = "Tel", name = "Tel", targetNamespace = "")
        java.lang.String tel,
        @WebParam(partName = "Mobile", name = "Mobile", targetNamespace = "")
        java.lang.String mobile,
        @WebParam(partName = "Email", name = "Email", targetNamespace = "")
        java.lang.String email,
        @WebParam(partName = "Memo", name = "Memo", targetNamespace = "")
        java.lang.String memo,
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pass", name = "Pass", targetNamespace = "")
        java.lang.String pass
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "HelloWorld")
    public java.lang.String helloWorld();

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetReportFail")
    public java.lang.String getReportFail(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "cell", name = "cell", targetNamespace = "")
        java.lang.String cell
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetMMS")
    public java.lang.String getMMS(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "AgentChangeAccount")
    public java.lang.String agentChangeAccount(
        @WebParam(partName = "LoginName", name = "LoginName", targetNamespace = "")
        java.lang.String loginName,
        @WebParam(partName = "LoginPwd", name = "LoginPwd", targetNamespace = "")
        java.lang.String loginPwd,
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "SmsBalance", name = "SmsBalance", targetNamespace = "")
        java.lang.String smsBalance,
        @WebParam(partName = "MmsBalance", name = "MmsBalance", targetNamespace = "")
        java.lang.String mmsBalance
    );

    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "ChargeUp")
    public int chargeUp(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "CardNo", name = "CardNo", targetNamespace = "")
        java.lang.String cardNo,
        @WebParam(partName = "CardPwd", name = "CardPwd", targetNamespace = "")
        java.lang.String cardPwd
    );

    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "Reg")
    public int reg(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "CorpName", name = "CorpName", targetNamespace = "")
        java.lang.String corpName,
        @WebParam(partName = "LinkMan", name = "LinkMan", targetNamespace = "")
        java.lang.String linkMan,
        @WebParam(partName = "Tel", name = "Tel", targetNamespace = "")
        java.lang.String tel,
        @WebParam(partName = "Mobile", name = "Mobile", targetNamespace = "")
        java.lang.String mobile,
        @WebParam(partName = "Email", name = "Email", targetNamespace = "")
        java.lang.String email,
        @WebParam(partName = "Memo", name = "Memo", targetNamespace = "")
        java.lang.String memo
    );

    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "UpdPwd")
    public int updPwd(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "NewPwd", name = "NewPwd", targetNamespace = "")
        java.lang.String newPwd
    );

    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "UnReg")
    public int unReg(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetReportSMS")
    public java.lang.String getReportSMS(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "SendMMS")
    public java.lang.String sendMMS(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "Mobile", name = "Mobile", targetNamespace = "")
        java.lang.String mobile,
        @WebParam(partName = "Base64Content", name = "Base64Content", targetNamespace = "")
        java.lang.String base64Content,
        @WebParam(partName = "Title", name = "Title", targetNamespace = "")
        java.lang.String title,
        @WebParam(partName = "ExtCode", name = "ExtCode", targetNamespace = "")
        java.lang.String extCode,
        @WebParam(partName = "SendTime", name = "SendTime", targetNamespace = "")
        java.lang.String sendTime
    );

    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "Send")
    public int send(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "Mobile", name = "Mobile", targetNamespace = "")
        java.lang.String mobile,
        @WebParam(partName = "Content", name = "Content", targetNamespace = "")
        java.lang.String content,
        @WebParam(partName = "Cell", name = "Cell", targetNamespace = "")
        java.lang.String cell,
        @WebParam(partName = "SendTime", name = "SendTime", targetNamespace = "")
        java.lang.String sendTime
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "Send2")
    public java.lang.String send2(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "Mobile", name = "Mobile", targetNamespace = "")
        java.lang.String mobile,
        @WebParam(partName = "Content", name = "Content", targetNamespace = "")
        java.lang.String content,
        @WebParam(partName = "Cell", name = "Cell", targetNamespace = "")
        java.lang.String cell,
        @WebParam(partName = "SendTime", name = "SendTime", targetNamespace = "")
        java.lang.String sendTime
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "BatchSendMMS")
    public java.lang.String batchSendMMS(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "Mobiles", name = "Mobiles", targetNamespace = "")
        java.lang.String mobiles,
        @WebParam(partName = "Base64Content", name = "Base64Content", targetNamespace = "")
        java.lang.String base64Content,
        @WebParam(partName = "Title", name = "Title", targetNamespace = "")
        java.lang.String title,
        @WebParam(partName = "ExtCode", name = "ExtCode", targetNamespace = "")
        java.lang.String extCode,
        @WebParam(partName = "SendTime", name = "SendTime", targetNamespace = "")
        java.lang.String sendTime
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "SendMMS2")
    public java.lang.String sendMMS2(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "Mobile", name = "Mobile", targetNamespace = "")
        java.lang.String mobile,
        @WebParam(partName = "Base64Content", name = "Base64Content", targetNamespace = "")
        java.lang.String base64Content,
        @WebParam(partName = "Title", name = "Title", targetNamespace = "")
        java.lang.String title,
        @WebParam(partName = "ExtCode", name = "ExtCode", targetNamespace = "")
        java.lang.String extCode,
        @WebParam(partName = "SendTime", name = "SendTime", targetNamespace = "")
        java.lang.String sendTime
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "BalanceMMS")
    public java.lang.String balanceMMS(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd
    );

    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "BatchSend")
    public int batchSend(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "Mobile", name = "Mobile", targetNamespace = "")
        java.lang.String mobile,
        @WebParam(partName = "Content", name = "Content", targetNamespace = "")
        java.lang.String content,
        @WebParam(partName = "Cell", name = "Cell", targetNamespace = "")
        java.lang.String cell,
        @WebParam(partName = "SendTime", name = "SendTime", targetNamespace = "")
        java.lang.String sendTime
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "BatchSendMMS2")
    public java.lang.String batchSendMMS2(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "Mobiles", name = "Mobiles", targetNamespace = "")
        java.lang.String mobiles,
        @WebParam(partName = "Base64Content", name = "Base64Content", targetNamespace = "")
        java.lang.String base64Content,
        @WebParam(partName = "Title", name = "Title", targetNamespace = "")
        java.lang.String title,
        @WebParam(partName = "ExtCode", name = "ExtCode", targetNamespace = "")
        java.lang.String extCode,
        @WebParam(partName = "SendTime", name = "SendTime", targetNamespace = "")
        java.lang.String sendTime
    );

    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "SelSum")
    public int selSum(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetReportMMS")
    public java.lang.String getReportMMS(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd
    );

    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "UpdReg")
    public int updReg(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "CorpName", name = "CorpName", targetNamespace = "")
        java.lang.String corpName,
        @WebParam(partName = "LinkMan", name = "LinkMan", targetNamespace = "")
        java.lang.String linkMan,
        @WebParam(partName = "Tel", name = "Tel", targetNamespace = "")
        java.lang.String tel,
        @WebParam(partName = "Mobile", name = "Mobile", targetNamespace = "")
        java.lang.String mobile,
        @WebParam(partName = "Email", name = "Email", targetNamespace = "")
        java.lang.String email,
        @WebParam(partName = "Memo", name = "Memo", targetNamespace = "")
        java.lang.String memo
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "GetReportFailMMS")
    public java.lang.String getReportFailMMS(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "cell", name = "cell", targetNamespace = "")
        java.lang.String cell
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "BatchSend2")
    public java.lang.String batchSend2(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "Mobile", name = "Mobile", targetNamespace = "")
        java.lang.String mobile,
        @WebParam(partName = "Content", name = "Content", targetNamespace = "")
        java.lang.String content,
        @WebParam(partName = "Cell", name = "Cell", targetNamespace = "")
        java.lang.String cell,
        @WebParam(partName = "SendTime", name = "SendTime", targetNamespace = "")
        java.lang.String sendTime
    );

    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "Get")
    public java.lang.String get(
        @WebParam(partName = "CorpID", name = "CorpID", targetNamespace = "")
        java.lang.String corpID,
        @WebParam(partName = "Pwd", name = "Pwd", targetNamespace = "")
        java.lang.String pwd
    );
}
