
package com.web.utils.suma;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2012-06-28T16:35:21.062+08:00
 * Generated source version: 2.3.7
 * 
 */
 
public class LinkWSHttpGet_LinkWSHttpGet_Server{

    protected LinkWSHttpGet_LinkWSHttpGet_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new LinkWSHttpGetImpl();
        String address = "http://120.132.132.133/WS/LinkWS.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new LinkWSHttpGet_LinkWSHttpGet_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
